//! What generated this, written when it is generated.
//!
//! ADR-2609221900. The six example projects record their test counts and
//! nothing about what produced them. That is unrecoverable — the runs and the
//! machines are gone — so the fix is upstream: a build says what produced its
//! output, in the directory it produces, at the moment it produces it.
//!
//! The hard part is not writing a file. It is writing one that does not claim
//! more than the runner knows. The runner does not record which model answered
//! each call, and a call that fell back to another tier is indistinguishable
//! from one that did not. A record saying "model X wrote this" would be a
//! confident record that is wrong in a way nobody can see — the failure this
//! project has spent its documentation on.

use hexa_exec::provenance::{record, write, Facts};

fn facts() -> Facts {
    Facts {
        date_utc: "2026-09-22T19:00:00Z".to_string(),
        hexa_version: "26.9.12".to_string(),
        challenge: "a URL shortener with a durable store".to_string(),
        gate: "cargo test".to_string(),
        gate_passed: true,
        designs: 3,
        critiques: 3,
        tiers: vec![
            ("t1".to_string(), "some-small-model".to_string()),
            ("t2".to_string(), "some-larger-model".to_string()),
        ],
        react_models: vec!["some-loop-model".to_string()],
    }
}

// ── What the record must carry ───────────────────────────────────────────────

#[test]
fn the_record_names_what_the_run_was() {
    let r = record(&facts());
    for needle in [
        "2026-09-22T19:00:00Z",
        "26.9.12",
        "a URL shortener with a durable store",
        "cargo test",
    ] {
        assert!(r.contains(needle), "the record must carry {needle}:\n{r}");
    }
}

#[test]
fn the_record_says_whether_the_gate_passed() {
    let passed = record(&facts());
    let mut f = facts();
    f.gate_passed = false;
    let failed = record(&f);
    assert_ne!(passed, failed, "a failed gate must not read like a passed one");
    assert!(
        failed.to_lowercase().contains("did not pass") || failed.to_lowercase().contains("failed"),
        "and it must say so in words:\n{failed}"
    );
}

#[test]
fn the_record_lists_the_resolved_tiers() {
    let r = record(&facts());
    for needle in ["t1", "some-small-model", "t2", "some-larger-model", "some-loop-model"] {
        assert!(r.contains(needle), "the resolved models are the point:\n{r}");
    }
}

// ── What the record must NOT claim ───────────────────────────────────────────

#[test]
fn the_record_states_its_own_limit() {
    // The whole reason this is honest rather than useful-looking.
    let r = record(&facts()).to_lowercase();
    assert!(
        r.contains("resolved") && r.contains("fall") || r.contains("not distinguish"),
        "the record must say it lists what resolved, not what answered each call:\n{r}"
    );
}

#[test]
fn the_limit_is_stated_even_when_everything_resolved() {
    // The tempting bug: drop the caveat when it looks like there is nothing to
    // caveat. The caveat is about what was never measured, not about failures.
    let r = record(&facts()).to_lowercase();
    assert!(r.contains("not distinguish") || r.contains("fall"), "{r}");
}

#[test]
fn a_run_with_no_tiers_still_produces_a_record() {
    // "Nothing resolved" is a fact worth recording, not a reason for an empty
    // file (ADR-2609122048).
    let mut f = facts();
    f.tiers.clear();
    f.react_models.clear();
    let r = record(&f);
    assert!(!r.trim().is_empty(), "a record is still written");
    assert!(
        r.to_lowercase().contains("none") || r.to_lowercase().contains("no tier"),
        "and it says nothing resolved, rather than listing nothing:\n{r}"
    );
}

#[test]
fn the_record_never_claims_a_model_wrote_the_code() {
    // The assertion is about attribution to a *model*, not about the word
    // "written": the record legitimately says it was written by the run that
    // generated the project. An earlier version of this test banned the
    // substring outright and failed on that sentence — the test was imprecise,
    // not the record.
    let f = facts();
    let r = record(&f).to_lowercase();
    let mut models: Vec<String> = f.tiers.iter().map(|(_, m)| m.to_lowercase()).collect();
    models.extend(f.react_models.iter().map(|m| m.to_lowercase()));
    for m in models {
        for claim in ["written by", "generated by", "authored by", "produced by"] {
            let phrase = format!("{claim} {m}");
            assert!(!r.contains(&phrase), "the runner cannot support `{phrase}`:\n{r}");
        }
    }
    assert!(
        r.contains("not as authorship"),
        "and the record says so in as many words:\n{r}"
    );
}

// ── The one side effect ──────────────────────────────────────────────────────

#[test]
fn write_puts_the_record_in_the_target() {
    let d = tempfile::tempdir().expect("tempdir");
    write(d.path(), &facts()).expect("write provenance");
    let p = d.path().join("PROVENANCE.md");
    assert!(p.is_file(), "PROVENANCE.md sits in the generated project");
    let text = std::fs::read_to_string(&p).unwrap();
    assert_eq!(text, record(&facts()), "the file is what the pure function returned");
}

#[test]
fn write_creates_the_directory_if_the_build_did_not() {
    let d = tempfile::tempdir().expect("tempdir");
    let nested = d.path().join("target-that-does-not-exist-yet");
    write(&nested, &facts()).expect("write provenance");
    assert!(nested.join("PROVENANCE.md").is_file(), "a failed build still gets a record");
}
