//! A primary HTTP adapter, generated from the contract (ADR-2610100005).
//!
//! Pure text: the contract and the names of where things live go in, one
//! source file comes out. The adapter drives one tagged port and imports
//! nothing else of the project. Go uses `net/http` and TypeScript
//! `node:http`, so neither takes on a dependency; Rust uses axum 0.8.
//!
//! What the generated code is judged by is not this file's tests but
//! `hexa api test` against a server built from it.

use std::collections::BTreeSet;

use super::domain::{capitalize, lower_camel, split_words, ApiArg, ApiContract, ApiOperation, ArgSource, TypeRef};

/// Where the adapter goes and how it reaches its port.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Target {
    /// `module`: the port's module path, `crate::ports`.
    Rust { module: String },
    /// `import`: the port package's import path; `package`: the adapter's own.
    Go { import: String, package: String },
    /// `import`: the port file, relative to the adapter, with `.js`.
    TypeScript { import: String },
}

/// The adapter for `port`, or why it cannot be generated.
pub fn generate(contract: &ApiContract, port: &str, target: &Target) -> Result<String, String> {
    let ops: Vec<&ApiOperation> = contract.operations.iter().filter(|o| o.port == port).collect();
    if ops.is_empty() {
        return Err(format!("`{port}` has no tagged operations"));
    }
    match target {
        Target::Rust { module } => rust(port, &ops, module),
        Target::Go { import, package } => go(port, &ops, import, package),
        Target::TypeScript { import } => Ok(typescript(port, &ops, import)),
    }
}

// ── Where things live ────────────────────────────────────

/// `src/ports/mod.rs` → `crate::ports`; `src/ports/api.rs` → `crate::ports::api`.
pub fn rust_module_of(port_file: &str) -> String {
    let rel = port_file.split_once("src/").map_or(port_file, |(_, r)| r);
    let rel = rel.strip_suffix(".rs").unwrap_or(rel);
    let rel = rel.strip_suffix("/mod").unwrap_or(rel);
    if rel == "lib" || rel == "main" {
        return "crate".into();
    }
    format!("crate::{}", rel.replace('/', "::"))
}

/// The import path of the Go package holding `port_file`, under `module`.
pub fn go_import_of(module: &str, port_file: &str) -> String {
    match port_file.rsplit_once('/') {
        Some((dir, _)) => format!("{module}/{dir}"),
        None => module.to_string(),
    }
}

/// A Go package name from the adapter's directory: `httpapi`.
pub fn go_package_of(out_file: &str) -> String {
    let dir = out_file.rsplit_once('/').map_or("main", |(d, _)| d);
    let last = dir.rsplit('/').next().unwrap_or(dir);
    let name: String = last.chars().filter(char::is_ascii_alphanumeric).collect::<String>().to_lowercase();
    if name.is_empty() || name.starts_with(|c: char| c.is_ascii_digit()) {
        format!("adapter{name}")
    } else {
        name
    }
}

/// The relative `.js` import from `out_file` to `port_file` (NodeNext).
pub fn ts_import_of(out_file: &str, port_file: &str) -> String {
    let from: Vec<&str> = out_file.split('/').collect();
    let to: Vec<&str> = port_file.split('/').collect();
    let from_dir = &from[..from.len().saturating_sub(1)];
    let common = from_dir.iter().zip(&to).take_while(|(a, b)| a == b).count();
    let ups = from_dir.len() - common;
    let mut parts: Vec<String> = Vec::new();
    if ups == 0 {
        parts.push(".".into());
    }
    parts.extend(std::iter::repeat_n("..".to_string(), ups));
    parts.extend(to[common..].iter().map(|s| s.to_string()));
    let joined = parts.join("/");
    let stem = joined.strip_suffix(".ts").unwrap_or(&joined);
    format!("{stem}.js")
}

/// Path segments of a route, in order.
fn segments(path: &str) -> Vec<String> {
    path.split('/')
        .filter_map(|s| s.strip_prefix('{').and_then(|s| s.strip_suffix('}')))
        .map(str::to_string)
        .collect()
}

fn pascal(name: &str) -> String {
    split_words(name).iter().map(|w| capitalize(w)).collect()
}

fn snake(name: &str) -> String {
    split_words(name).join("_")
}

const HEADER: &str = "generated by `hexa api adapter` from its `@hexa:api` contract (ADR-2610100005).\n\
It drives the port and imports nothing else of the project; the composition\n\
root hands it the port's implementation. It is generated once and belongs to\n\
the project: edit it like any adapter, and prove it with `hexa api test`.";

// ── Rust: axum 0.8 ───────────────────────────────────────

/// The owned type to extract for a parameter written as `written`, and how
/// to pass the extracted value back to the method.
fn rust_owned(written: &str) -> (String, &'static str) {
    let w = written.trim();
    if w == "Option<&str>" {
        return ("Option<String>".into(), ".as_deref()");
    }
    let Some(rest) = w.strip_prefix('&') else {
        return (w.to_string(), "");
    };
    let rest = rest.trim_start();
    let rest = if rest.starts_with('\'') { rest.split_once(' ').map_or(rest, |(_, r)| r) } else { rest };
    let rest = rest.strip_prefix("mut ").unwrap_or(rest).trim();
    let owned = if rest == "str" {
        "String".to_string()
    } else if let Some(inner) = rest.strip_prefix('[').and_then(|r| r.strip_suffix(']')) {
        format!("Vec<{inner}>")
    } else {
        rest.to_string()
    };
    (owned, "&")
}

fn rust_status(code: u16) -> String {
    match code {
        200 => "StatusCode::OK".into(),
        201 => "StatusCode::CREATED".into(),
        202 => "StatusCode::ACCEPTED".into(),
        204 => "StatusCode::NO_CONTENT".into(),
        400 => "StatusCode::BAD_REQUEST".into(),
        401 => "StatusCode::UNAUTHORIZED".into(),
        403 => "StatusCode::FORBIDDEN".into(),
        404 => "StatusCode::NOT_FOUND".into(),
        409 => "StatusCode::CONFLICT".into(),
        422 => "StatusCode::UNPROCESSABLE_ENTITY".into(),
        500 => "StatusCode::INTERNAL_SERVER_ERROR".into(),
        503 => "StatusCode::SERVICE_UNAVAILABLE".into(),
        other => format!("StatusCode::from_u16({other}).unwrap_or(StatusCode::INTERNAL_SERVER_ERROR)"),
    }
}

fn rust(port: &str, ops: &[&ApiOperation], module: &str) -> Result<String, String> {
    let mut out = String::new();
    let bound = format!("S: {port} + Send + Sync + 'static");
    let mut routing: BTreeSet<String> = BTreeSet::new();
    let mut extract: BTreeSet<&str> = BTreeSet::from(["State"]);
    let mut rejections: BTreeSet<&str> = BTreeSet::new();
    let mut needs_deserialize = false;
    let mut handlers = String::new();
    let mut error_types: Vec<(String, Vec<(String, u16)>)> = Vec::new();

    for op in ops {
        let handler = format!("handle_{}", snake(&op.method_name));
        let mut params = vec!["State(api): State<Arc<S>>".to_string()];
        let mut binds = Vec::new();
        let mut call = Vec::new();

        let path_args: Vec<&ApiArg> = segments(&op.path)
            .iter()
            .filter_map(|seg| op.args.iter().find(|a| a.source == ArgSource::Path(seg.clone())))
            .collect();
        if !path_args.is_empty() {
            extract.insert("Path");
            rejections.insert("PathRejection");
            let types: Vec<String> = path_args.iter().map(|a| rust_owned(&a.written).0).collect();
            let names: Vec<String> = path_args.iter().map(|a| a.name.clone()).collect();
            let (ty, pat) = if types.len() == 1 {
                (types[0].clone(), names[0].clone())
            } else {
                (format!("({})", types.join(", ")), format!("({})", names.join(", ")))
            };
            params.push(format!("path: Result<Path<{ty}>, PathRejection>"));
            binds.push(format!("    let Ok(Path({pat})) = path else {{\n        return bad_request();\n    }};"));
        }

        let query_args: Vec<&ApiArg> = op.args.iter().filter(|a| matches!(a.source, ArgSource::Query(_))).collect();
        let mut structs = String::new();
        if !query_args.is_empty() {
            if let Some(a) = query_args.iter().find(|a| matches!(a.ty, TypeRef::Array(_))) {
                return Err(format!(
                    "`{} {}`: the list query parameter `{}` cannot be read by axum's query extractor",
                    op.http_method, op.path, a.name
                ));
            }
            extract.insert("Query");
            rejections.insert("QueryRejection");
            needs_deserialize = true;
            let name = format!("{}Query", pascal(&op.method_name));
            structs.push_str(&format!("/// The query of `{} {}`.\n#[derive(Deserialize)]\nstruct {name} {{\n", op.http_method, op.path));
            for a in &query_args {
                let ArgSource::Query(wire) = &a.source else { continue };
                structs.push_str(&format!("    #[serde(rename = \"{wire}\")]\n    {}: {},\n", a.name, rust_owned(&a.written).0));
            }
            structs.push_str("}\n\n");
            params.push(format!("query: Result<Query<{name}>, QueryRejection>"));
            binds.push("    let Ok(Query(query)) = query else {\n        return bad_request();\n    };".into());
        }

        let fields: Vec<&ApiArg> = op.args.iter().filter(|a| matches!(a.source, ArgSource::BodyField(_))).collect();
        if let Some(whole) = op.args.iter().find(|a| a.source == ArgSource::Body) {
            extract.insert("Json");
            rejections.insert("JsonRejection");
            params.push(format!("body: Result<Json<{}>, JsonRejection>", rust_owned(&whole.written).0));
            binds.push("    let Ok(Json(body)) = body else {\n        return bad_request();\n    };".into());
        } else if !fields.is_empty() {
            extract.insert("Json");
            rejections.insert("JsonRejection");
            needs_deserialize = true;
            let name = format!("{}Body", pascal(&op.method_name));
            structs.push_str(&format!("/// The body of `{} {}`.\n#[derive(Deserialize)]\nstruct {name} {{\n", op.http_method, op.path));
            for a in &fields {
                let ArgSource::BodyField(wire) = &a.source else { continue };
                structs.push_str(&format!("    #[serde(rename = \"{wire}\")]\n    {}: {},\n", a.name, rust_owned(&a.written).0));
            }
            structs.push_str("}\n\n");
            params.push(format!("body: Result<Json<{name}>, JsonRejection>"));
            binds.push("    let Ok(Json(body)) = body else {\n        return bad_request();\n    };".into());
        }

        for a in &op.args {
            let (_, pass) = rust_owned(&a.written);
            let value = match &a.source {
                ArgSource::Path(_) => a.name.clone(),
                ArgSource::Query(_) => format!("query.{}", a.name),
                ArgSource::BodyField(_) => format!("body.{}", a.name),
                ArgSource::Body => "body".into(),
                ArgSource::Context => continue,
            };
            call.push(match pass {
                "&" => format!("&{value}"),
                ".as_deref()" => format!("{value}.as_deref()"),
                _ => value,
            });
        }
        let await_ = if op.is_async { ".await" } else { "" };
        let invoke = format!("api.{}({}){await_}", op.method_name, call.join(", "));
        let ok = rust_status(op.success);
        let answer = |v: &str| match op.response {
            Some(_) => format!("({ok}, Json({v})).into_response()"),
            None => format!("{ok}.into_response()"),
        };
        let body = if op.fails {
            let on_err = match &op.error_type {
                Some(e) => {
                    if !error_types.iter().any(|(n, _)| n == e) {
                        error_types.push((e.clone(), op.error_variants.clone()));
                    }
                    format!("error_response_{}(&error)", snake(e))
                }
                None => "status_response(StatusCode::INTERNAL_SERVER_ERROR)".into(),
            };
            let ok_pat = if op.response.is_some() { "Ok(value)" } else { "Ok(_)" };
            let err_pat = if op.error_type.is_some() { "Err(error)" } else { "Err(_)" };
            format!("    match {invoke} {{\n        {ok_pat} => {},\n        {err_pat} => {on_err},\n    }}", answer("value"))
        } else if op.response.is_some() {
            format!("    let value = {invoke};\n    {}", answer("value"))
        } else {
            format!("    {invoke};\n    {}", answer(""))
        };
        let mut binds_text = binds.join("\n");
        if !binds_text.is_empty() {
            binds_text.push('\n');
        }
        handlers.push_str(&structs);
        handlers.push_str(&format!(
            "/// `{} {}` → `{port}::{}`.\nasync fn {handler}<{bound}>(\n    {},\n) -> Response {{\n{binds_text}{body}\n}}\n\n",
            op.http_method,
            op.path,
            op.method_name,
            params.join(",\n    ")
        ));
    }

    // Routes, grouped by path in the order they are declared.
    let mut paths: Vec<&str> = Vec::new();
    for op in ops {
        if !paths.contains(&op.path.as_str()) {
            paths.push(&op.path);
        }
    }
    let mut routes = String::new();
    for p in &paths {
        let chain: Vec<String> = ops
            .iter()
            .filter(|o| o.path == *p)
            .map(|o| {
                let f = o.http_method.to_lowercase();
                format!("{f}(handle_{}::<S>)", snake(&o.method_name))
            })
            .collect();
        let first = chain[0].split('(').next().unwrap_or("get").to_string();
        routing.insert(first);
        let rest: Vec<String> = chain[1..].iter().map(|c| format!(".{c}")).collect();
        routes.push_str(&format!("        .route(\"{p}\", {}{})\n", chain[0], rest.join("")));
    }

    out.push_str(&format!("//! The HTTP adapter for `{port}`, {}\n", HEADER.replace('\n', "\n//! ")));
    out.push_str("//!\n//! Needs axum 0.8, serde (derive) and tokio.\n");
    if ops.iter().any(|o| !o.is_async) {
        out.push_str(
            "//!\n//! A sync port method is called on the runtime's thread: right for in-memory\n//! work. Wrap blocking I/O in `tokio::task::spawn_blocking`, as\n//! `examples/linkstore-svc` does.\n",
        );
    }
    out.push_str("\nuse std::sync::Arc;\n\n");
    let mut rej: Vec<&str> = rejections.into_iter().collect();
    rej.sort_unstable();
    if !rej.is_empty() {
        out.push_str(&format!("use axum::extract::rejection::{{{}}};\n", rej.join(", ")));
    }
    let ex: Vec<&str> = extract.iter().copied().filter(|e| *e != "Json").collect();
    out.push_str(&format!("use axum::extract::{{{}}};\n", ex.join(", ")));
    out.push_str("use axum::http::StatusCode;\nuse axum::response::{IntoResponse, Response};\n");
    out.push_str(&format!("use axum::routing::{{{}}};\n", routing.into_iter().collect::<Vec<_>>().join(", ")));
    out.push_str("use axum::{Json, Router};\n");
    out.push_str(if needs_deserialize { "use serde::{Deserialize, Serialize};\n\n" } else { "use serde::Serialize;\n\n" });
    out.push_str(&format!("// The port's module, re-exports included, as the port itself sees it.\n#[allow(unused_imports)]\nuse {module}::*;\n\n"));
    out.push_str(&format!(
        "/// The contract's routes, served by `api`.\npub fn router<{bound}>(api: Arc<S>) -> Router {{\n    Router::new()\n{routes}        .with_state(api)\n}}\n\n"
    ));
    out.push_str(&handlers);
    for (e, variants) in &error_types {
        out.push_str(&format!("/// Each `{e}` variant answers with its `@hexa:status`; the rest with 500.\nfn error_response_{}(error: &{e}) -> Response {{\n    let status = match error {{\n", snake(e)));
        for (ident, code) in variants {
            out.push_str(&format!("        {e}::{ident} {{ .. }} => {},\n", rust_status(*code)));
        }
        out.push_str("    };\n    status_response(status)\n}\n\n");
    }
    out.push_str(
        "/// Malformed input: a path, query or body that does not parse.\nfn bad_request() -> Response {\n    status_response(StatusCode::BAD_REQUEST)\n}\n\n\
#[derive(Serialize)]\nstruct ErrorBody {\n    error: &'static str,\n}\n\n\
fn status_response(status: StatusCode) -> Response {\n    let error = status.canonical_reason().unwrap_or(\"error\");\n    (status, Json(ErrorBody { error })).into_response()\n}\n",
    );
    Ok(out)
}

// ── Go: net/http ─────────────────────────────────────────

/// Qualify the port package's own types in a Go type as written.
fn go_qualify(written: &str, package: &str) -> String {
    let mut out = String::new();
    let chars: Vec<char> = written.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        let c = chars[i];
        if c.is_alphabetic() || c == '_' {
            let start = i;
            while i < chars.len() && (chars[i].is_alphanumeric() || chars[i] == '_') {
                i += 1;
            }
            let word: String = chars[start..i].iter().collect();
            let qualified_before = start > 0 && chars[start - 1] == '.';
            let qualifier_after = chars.get(i) == Some(&'.');
            if word.starts_with(char::is_uppercase) && !qualified_before && !qualifier_after {
                out.push_str(&format!("{package}.{word}"));
            } else {
                out.push_str(&word);
            }
        } else {
            out.push(c);
            i += 1;
        }
    }
    out
}

/// Go statements that parse `raw` (a string expression) into `var` of
/// `written`, answering 400 when it does not parse.
fn go_parse(var: &str, raw: &str, a: &ApiArg, package: &str, uses: &mut BTreeSet<&'static str>) -> Result<String, String> {
    let ty = go_qualify(a.written.trim_start_matches('*'), package);
    let fail = "\t\t\twriteStatus(w, http.StatusBadRequest)\n\t\t\treturn\n";
    Ok(match &a.ty {
        TypeRef::String => format!("\t\t{var} := {ty}({raw})\n"),
        TypeRef::Integer => {
            uses.insert("strconv");
            // Parse at the written type's own width so an overflow is a 400, not a silent wrap.
            let (parse, bits) = match a.written.trim_start_matches('*') {
                "int" => ("ParseInt", 0),
                "int8" => ("ParseInt", 8),
                "int16" => ("ParseInt", 16),
                "int32" | "rune" => ("ParseInt", 32),
                "uint" => ("ParseUint", 0),
                "uint8" | "byte" => ("ParseUint", 8),
                "uint16" => ("ParseUint", 16),
                "uint32" => ("ParseUint", 32),
                "uint64" | "uintptr" => ("ParseUint", 64),
                _ => ("ParseInt", 64),
            };
            format!("\t\tn{var}, err := strconv.{parse}({raw}, 10, {bits})\n\t\tif err != nil {{\n{fail}\t\t}}\n\t\t{var} := {ty}(n{var})\n")
        }
        TypeRef::Number => {
            uses.insert("strconv");
            format!("\t\tn{var}, err := strconv.ParseFloat({raw}, 64)\n\t\tif err != nil {{\n{fail}\t\t}}\n\t\t{var} := {ty}(n{var})\n")
        }
        TypeRef::Boolean => {
            uses.insert("strconv");
            format!("\t\tb{var}, err := strconv.ParseBool({raw})\n\t\tif err != nil {{\n{fail}\t\t}}\n\t\t{var} := {ty}(b{var})\n")
        }
        other => return Err(format!("`{}`: a {other:?} cannot be read from a path or query string", a.name)),
    })
}

const GO_PORT_ALIAS: &str = "ports";

fn go(port: &str, ops: &[&ApiOperation], import: &str, package: &str) -> Result<String, String> {
    // The import path cannot name the package (`ports/v2`, `my-ports`, a module
    // ending `/v2`), so import it under a fixed alias instead of guessing.
    let pkg = GO_PORT_ALIAS;
    let mut uses: BTreeSet<&'static str> = BTreeSet::from(["encoding/json", "errors", "net/http"]);
    let mut body = String::new();
    for op in ops {
        let mut s = String::new();
        s.push_str(&format!(
            "\t// {} {} → {port}.{}\n\tmux.HandleFunc(\"{} {}\", func(w http.ResponseWriter, r *http.Request) {{\n",
            op.http_method, op.path, op.method_name, op.http_method, op.path
        ));
        let has_query = op.args.iter().any(|a| matches!(a.source, ArgSource::Query(_)));
        if has_query {
            s.push_str("\t\tq := r.URL.Query()\n");
        }
        let fields: Vec<&ApiArg> = op.args.iter().filter(|a| matches!(a.source, ArgSource::BodyField(_))).collect();
        let mut call = Vec::new();
        for a in &op.args {
            let var = format!("arg{}", pascal(&a.name));
            match &a.source {
                ArgSource::Context => {
                    call.push("r.Context()".to_string());
                    continue;
                }
                ArgSource::Path(seg) => s.push_str(&go_parse(&var, &format!("r.PathValue(\"{seg}\")"), a, pkg, &mut uses)?),
                ArgSource::Query(wire) => {
                    let pointer = a.written.trim_start().starts_with('*');
                    if let TypeRef::Array(e) = &a.ty {
                        if **e != TypeRef::String {
                            return Err(format!("`{} {}`: only a list of strings is read from a query", op.http_method, op.path));
                        }
                        s.push_str(&format!("\t\t{var} := q[\"{wire}\"]\n"));
                    } else if pointer || !a.required {
                        s.push_str(&format!("\t\tvar {var} {}\n\t\tif q.Has(\"{wire}\") {{\n", go_qualify(&a.written, pkg)));
                        let inner = go_parse("v", &format!("q.Get(\"{wire}\")"), a, pkg, &mut uses)?;
                        s.push_str(&inner.replace("\n\t\t", "\n\t\t\t").replacen("\t\t", "\t\t\t", 1));
                        s.push_str(&format!("\t\t\t{var} = {}v\n\t\t}}\n", if pointer { "&" } else { "" }));
                    } else {
                        s.push_str(&format!("\t\tif !q.Has(\"{wire}\") {{\n\t\t\twriteStatus(w, http.StatusBadRequest)\n\t\t\treturn\n\t\t}}\n"));
                        s.push_str(&go_parse(&var, &format!("q.Get(\"{wire}\")"), a, pkg, &mut uses)?);
                    }
                }
                ArgSource::Body => {
                    s.push_str(&format!(
                        "\t\tvar {var} {}\n\t\tif err := decodeBody(w, r, &{var}); err != nil {{\n\t\t\twriteStatus(w, http.StatusBadRequest)\n\t\t\treturn\n\t\t}}\n",
                        go_qualify(&a.written, pkg)
                    ));
                }
                ArgSource::BodyField(_) => {
                    call.push(format!("body.{}", pascal(&a.name)));
                    continue;
                }
            }
            call.push(var);
        }
        if !fields.is_empty() {
            let mut decl = String::from("\t\tvar body struct {\n");
            for a in &fields {
                let ArgSource::BodyField(wire) = &a.source else { continue };
                decl.push_str(&format!("\t\t\t{} {} `json:\"{wire}\"`\n", pascal(&a.name), go_qualify(&a.written, pkg)));
            }
            decl.push_str("\t\t}\n\t\tif err := decodeBody(w, r, &body); err != nil {\n\t\t\twriteStatus(w, http.StatusBadRequest)\n\t\t\treturn\n\t\t}\n");
            s.push_str(&decl);
        }
        let invoke = format!("api.{}({})", op.method_name, call.join(", "));
        let answer = match op.response {
            Some(_) => format!("\t\twriteJSON(w, {}, out)\n", op.success),
            None => format!("\t\tw.WriteHeader({})\n", op.success),
        };
        match (op.fails, op.response.is_some()) {
            (true, true) => s.push_str(&format!("\t\tout, err := {invoke}\n\t\tif err != nil {{\n\t\t\twriteError(w, err)\n\t\t\treturn\n\t\t}}\n{answer}")),
            (true, false) => s.push_str(&format!("\t\tif err := {invoke}; err != nil {{\n\t\t\twriteError(w, err)\n\t\t\treturn\n\t\t}}\n{answer}")),
            (false, true) => s.push_str(&format!("\t\tout := {invoke}\n{answer}")),
            (false, false) => s.push_str(&format!("\t\t{invoke}\n{answer}")),
        }
        s.push_str("\t})\n\n");
        body.push_str(&s);
    }
    let mut out = format!("// Package {package} is the HTTP adapter for {port}, {}\n", HEADER.replace('\n', "\n// "));
    out.push_str("//\n// An error reports its HTTP status by having an HTTPStatus() int method;\n// any other error is 500.\n");
    out.push_str(&format!("package {package}\n\nimport (\n"));
    for u in &uses {
        out.push_str(&format!("\t\"{u}\"\n"));
    }
    out.push_str(&format!("\n\t{pkg} \"{import}\"\n)\n\n"));
    out.push_str(&format!(
        "// NewHandler serves the contract's routes from api.\nfunc NewHandler(api {pkg}.{port}) http.Handler {{\n\tmux := http.NewServeMux()\n\n{body}\treturn mux\n}}\n\n"
    ));
    out.push_str(
        "type httpStatuser interface{ HTTPStatus() int }\n\n\
// writeError answers with the error's own status, or 500.\nfunc writeError(w http.ResponseWriter, err error) {\n\tstatus := http.StatusInternalServerError\n\tvar s httpStatuser\n\tif errors.As(err, &s) {\n\t\tstatus = s.HTTPStatus()\n\t}\n\twriteStatus(w, status)\n}\n\n\
func writeStatus(w http.ResponseWriter, status int) {\n\twriteJSON(w, status, map[string]string{\"error\": http.StatusText(status)})\n}\n\n\
// maxBodyBytes caps a request body, as axum's `Json` does (2 MB).\nconst maxBodyBytes = 2 << 20\n\n// decodeBody reads a bounded JSON body; one past the cap fails the decode.\nfunc decodeBody(w http.ResponseWriter, r *http.Request, v any) error {\n\treturn json.NewDecoder(http.MaxBytesReader(w, r.Body, maxBodyBytes)).Decode(v)\n}\n\nfunc writeJSON(w http.ResponseWriter, status int, v any) {\n\tw.Header().Set(\"Content-Type\", \"application/json\")\n\tw.WriteHeader(status)\n\t_ = json.NewEncoder(w).Encode(v)\n}\n",
    );
    Ok(out)
}

// ── TypeScript: node:http ────────────────────────────────

fn typescript(port: &str, ops: &[&ApiOperation], import: &str) -> String {
    let mut routes = String::new();
    // First match wins, so a literal segment must be tried before a `{param}` one
    // (axum and ServeMux prefer the literal path); the sort is stable otherwise.
    let mut ops: Vec<&ApiOperation> = ops.to_vec();
    ops.sort_by_key(|op| op.path.split('/').filter(|s| !s.is_empty()).map(|s| s.starts_with('{')).collect::<Vec<_>>());
    for op in ops {
        let param = |i: usize| format!("Parameters<{port}['{}']>[{i}]", op.method_name);
        let mut lines = Vec::new();
        let mut call = Vec::new();
        let fields = op.args.iter().any(|a| matches!(a.source, ArgSource::BodyField(_)));
        if fields {
            lines.push("const fields = await readObject(req);".to_string());
        }
        for (i, a) in op.args.iter().enumerate() {
            let var = lower_camel(&format!("arg_{}", a.name));
            match &a.source {
                ArgSource::Path(seg) => lines.push(format!("const {var} = {} as {};", ts_convert(&format!("params['{seg}']"), &a.ty), param(i))),
                ArgSource::Query(wire) => {
                    let raw = if matches!(a.ty, TypeRef::Array(_)) {
                        format!("url.searchParams.getAll('{wire}')")
                    } else {
                        format!("url.searchParams.get('{wire}')")
                    };
                    if a.required && !matches!(a.ty, TypeRef::Array(_)) {
                        lines.push(format!("const raw{} = {raw};", pascal(&a.name)));
                        lines.push(format!("if (raw{} === null) throw new BadRequest();", pascal(&a.name)));
                        lines.push(format!("const {var} = {} as {};", ts_convert(&format!("raw{}", pascal(&a.name)), &a.ty), param(i)));
                    } else if matches!(a.ty, TypeRef::Array(_)) {
                        lines.push(format!("const {var} = {raw} as {};", param(i)));
                    } else {
                        lines.push(format!("const raw{} = {raw};", pascal(&a.name)));
                        lines.push(format!(
                            "const {var} = (raw{0} === null ? undefined : {1}) as {2};",
                            pascal(&a.name),
                            ts_convert(&format!("raw{}", pascal(&a.name)), &a.ty),
                            param(i)
                        ));
                    }
                }
                ArgSource::Body => lines.push(format!("const {var} = (await readJson(req)) as {};", param(i))),
                ArgSource::BodyField(wire) => lines.push(format!("const {var} = fields['{wire}'] as {};", param(i))),
                ArgSource::Context => continue,
            }
            call.push(var);
        }
        let invoke = format!("await api.{}({})", op.method_name, call.join(", "));
        match op.response {
            Some(_) => {
                lines.push(format!("const out = {invoke};"));
                lines.push(format!("send(res, {}, out);", op.success));
            }
            None => {
                lines.push(format!("{invoke};"));
                lines.push(format!("send(res, {});", op.success));
            }
        }
        lines.push("return;".into());
        let uses_params = op.args.iter().any(|a| matches!(a.source, ArgSource::Path(_)));
        let binding = if uses_params { "params" } else { "_params" };
        routes.push_str(&format!(
            "  // {} {} → {port}.{}\n  {{\n    const {binding} = req.method === '{}' ? match('{}', url.pathname) : null;\n    if ({binding}) {{\n{}\n    }}\n  }}\n",
            op.http_method,
            op.path,
            op.method_name,
            op.http_method,
            op.path,
            lines.iter().map(|l| format!("      {l}")).collect::<Vec<_>>().join("\n")
        ));
    }
    let mut out = String::new();
    out.push_str(&format!("/**\n * The HTTP adapter for `{port}`, {}\n *\n * A thrown value with an integer `status` of 400-599 answers with it; anything else is 500.\n */\n", HEADER.replace('\n', "\n * ")));
    out.push_str("import type { IncomingMessage, ServerResponse } from 'node:http';\n");
    out.push_str(&format!("import type {{ {port} }} from '{import}';\n\n"));
    out.push_str("type Handler = (req: IncomingMessage, res: ServerResponse) => void;\n\n");
    out.push_str("/** Malformed input: a path, query or body that does not parse. */\nclass BadRequest extends Error {\n  readonly status = 400;\n  constructor() {\n    super('Bad Request');\n  }\n}\n\n");
    out.push_str("/** A request body past the cap (2 MB, as axum's `Json` does). */\nconst MAX_BODY_BYTES = 2 * 1024 * 1024;\n\nclass PayloadTooLarge extends Error {\n  readonly status = 413;\n  constructor() {\n    super('Payload Too Large');\n  }\n}\n\n");
    out.push_str(&format!(
        "/** The contract's routes, served by `api`. */\nexport function createHandler(api: {port}): Handler {{\n  return (req, res) => {{\n    route(api, req, res).catch((error: unknown) => sendError(res, error));\n  }};\n}}\n\n"
    ));
    out.push_str(&format!(
        "async function route(api: {port}, req: IncomingMessage, res: ServerResponse): Promise<void> {{\n  const url = new URL(req.url ?? '/', 'http://localhost');\n{routes}  send(res, 404, {{ error: 'Not Found' }});\n}}\n\n"
    ));
    out.push_str(
        "function match(pattern: string, path: string): Record<string, string> | null {\n  const want = pattern.split('/').filter(Boolean);\n  const got = path.split('/').filter(Boolean);\n  if (want.length !== got.length) return null;\n  const params: Record<string, string> = {};\n  for (let i = 0; i < want.length; i++) {\n    const w = want[i] ?? '';\n    const g = got[i] ?? '';\n    if (w.startsWith('{')) params[w.slice(1, -1)] = decodePathSegment(g);\n    else if (w !== g) return null;\n  }\n  return params;\n}\n\n\
function decodePathSegment(raw: string): string {\n  try {\n    return decodeURIComponent(raw);\n  } catch {\n    throw new BadRequest();\n  }\n}\n\n\
async function readJson(req: IncomingMessage): Promise<unknown> {\n  const chunks: Buffer[] = [];\n  let size = 0;\n  for await (const chunk of req) {\n    size += (chunk as Buffer).length;\n    if (size > MAX_BODY_BYTES) throw new PayloadTooLarge();\n    chunks.push(chunk as Buffer);\n  }\n  let body: unknown;\n  try {\n    body = JSON.parse(Buffer.concat(chunks).toString('utf8'));\n  } catch {\n    throw new BadRequest();\n  }\n  if (body === null) throw new BadRequest();\n  return body;\n}\n\n\
async function readObject(req: IncomingMessage): Promise<Record<string, unknown>> {\n  const body = await readJson(req);\n  if (typeof body !== 'object' || Array.isArray(body)) throw new BadRequest();\n  return body as Record<string, unknown>;\n}\n\n\
function toNumber(raw: string): number {\n  const n = Number(raw);\n  if (raw.trim() === '' || Number.isNaN(n)) throw new BadRequest();\n  return n;\n}\n\n\
function toInteger(raw: string): number {\n  if (!/^[+-]?[0-9]+$/.test(raw)) throw new BadRequest();\n  const n = Number(raw);\n  if (!Number.isSafeInteger(n)) throw new BadRequest();\n  return n;\n}\n\n\
function toBoolean(raw: string): boolean {\n  if (raw === 'true') return true;\n  if (raw === 'false') return false;\n  throw new BadRequest();\n}\n\n\
function send(res: ServerResponse, status: number, body?: unknown): void {\n  if (body === undefined) {\n    res.writeHead(status).end();\n    return;\n  }\n  res.writeHead(status, { 'Content-Type': 'application/json' }).end(JSON.stringify(body));\n}\n\n\
function sendError(res: ServerResponse, error: unknown): void {\n  if (res.headersSent) {\n    res.destroy();\n    return;\n  }\n  const status = (error as { status?: unknown } | null)?.status;\n  const code = typeof status === 'number' && Number.isInteger(status) && status >= 400 && status <= 599 ? status : 500;\n  send(res, code, { error: code === 500 ? 'Internal Server Error' : String((error as Error | null)?.message ?? code) });\n}\n",
    );
    out
}

fn ts_convert(raw: &str, ty: &TypeRef) -> String {
    match ty {
        TypeRef::Integer => format!("toInteger({raw})"),
        TypeRef::Number => format!("toNumber({raw})"),
        TypeRef::Boolean => format!("toBoolean({raw})"),
        _ => raw.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn where_things_live() {
        assert_eq!(rust_module_of("src/ports/mod.rs"), "crate::ports");
        assert_eq!(rust_module_of("src/ports/api.rs"), "crate::ports::api");
        assert_eq!(rust_module_of("crates/x/src/lib.rs"), "crate");
        assert_eq!(go_import_of("bookmarks", "internal/ports/api.go"), "bookmarks/internal/ports");
        assert_eq!(go_package_of("adapters/primary/httpapi/handler.go"), "httpapi");
        assert_eq!(go_package_of("adapters/primary/http-api/handler.go"), "httpapi");
        assert_eq!(
            ts_import_of("src/adapters/primary/http-handler.ts", "src/core/ports/bookmark-api.ts"),
            "../../core/ports/bookmark-api.js"
        );
        assert_eq!(ts_import_of("src/ports/h.ts", "src/ports/api.ts"), "./api.js");
    }

    #[test]
    fn rust_parameters_are_extracted_owned_and_passed_as_written() {
        assert_eq!(rust_owned("&str"), ("String".into(), "&"));
        assert_eq!(rust_owned("&'a str"), ("String".into(), "&"));
        assert_eq!(rust_owned("&[String]"), ("Vec<String>".into(), "&"));
        assert_eq!(rust_owned("Option<&str>"), ("Option<String>".into(), ".as_deref()"));
        assert_eq!(rust_owned("NewBookmark"), ("NewBookmark".into(), ""));
    }

    #[test]
    fn go_types_of_the_port_package_are_qualified() {
        assert_eq!(go_qualify("NewBookmark", "ports"), "ports.NewBookmark");
        assert_eq!(go_qualify("*string", "ports"), "*string");
        assert_eq!(go_qualify("[]Tag", "ports"), "[]ports.Tag");
        assert_eq!(go_qualify("map[string]Tag", "ports"), "map[string]ports.Tag");
        assert_eq!(go_qualify("time.Time", "ports"), "time.Time");
    }

    #[test]
    fn go_port_import_is_aliased_not_named_after_its_path() {
        let op = ApiOperation {
            service: "Bookmarks".into(),
            port: "BookmarkApi".into(),
            method_name: "add".into(),
            operation_id: "add".into(),
            http_method: "POST".into(),
            path: "/bookmarks".into(),
            description: String::new(),
            params: vec![],
            body: None,
            success: 201,
            response: None,
            errors: vec![],
            file: "api.go".into(),
            line: 1,
            args: vec![ApiArg { name: "input".into(), written: "NewBookmark".into(), source: ArgSource::Body, ty: TypeRef::String, required: true }],
            is_async: true,
            fails: false,
            error_type: None,
            error_variants: vec![],
        };
        let contract = ApiContract { title: "t".into(), version: "1".into(), operations: vec![op], schemas: Default::default() };
        for import in ["example.com/x/ports/v2", "example.com/x/my-ports", "example.com/foo/v2"] {
            let target = Target::Go { import: import.into(), package: "httpapi".into() };
            let go = generate(&contract, "BookmarkApi", &target).unwrap();
            assert!(go.contains(&format!("\tports \"{import}\"\n")), "{go}");
            assert!(go.contains("api ports.BookmarkApi"), "{go}");
            assert!(!go.contains("v2.") && !go.contains("my-ports."), "{go}");
        }
    }

    #[test]
    fn go_integers_are_parsed_at_the_written_width() {
        let arg = |written: &str| ApiArg {
            name: "n".into(),
            written: written.into(),
            source: ArgSource::Path("n".into()),
            ty: TypeRef::Integer,
            required: true,
        };
        let parse = |written: &str| go_parse("argN", "raw", &arg(written), "ports", &mut BTreeSet::new()).unwrap();
        assert!(parse("uint8").contains("strconv.ParseUint(raw, 10, 8)"), "{}", parse("uint8"));
        assert!(parse("uint").contains("strconv.ParseUint(raw, 10, 0)"), "{}", parse("uint"));
        assert!(parse("int32").contains("strconv.ParseInt(raw, 10, 32)"), "{}", parse("int32"));
        assert!(parse("*int16").contains("strconv.ParseInt(raw, 10, 16)"), "{}", parse("*int16"));
        assert!(parse("int64").contains("strconv.ParseInt(raw, 10, 64)"), "{}", parse("int64"));
    }

    #[test]
    fn typescript_bad_request_carries_the_bad_request_message() {
        let op = ApiOperation {
            service: "Bookmarks".into(),
            port: "BookmarkApi".into(),
            method_name: "get".into(),
            operation_id: "get".into(),
            http_method: "GET".into(),
            path: "/bookmarks/{id}".into(),
            description: String::new(),
            params: vec![],
            body: None,
            success: 200,
            response: None,
            errors: vec![],
            file: "api.ts".into(),
            line: 1,
            args: vec![],
            is_async: true,
            fails: false,
            error_type: None,
            error_variants: vec![],
        };
        let contract = ApiContract {
            title: "t".into(),
            version: "1".into(),
            operations: vec![op],
            schemas: Default::default(),
        };
        let target = Target::TypeScript { import: "./api.js".into() };
        let out = generate(&contract, "BookmarkApi", &target).unwrap();
        let class = out.split("class BadRequest").nth(1).expect("BadRequest is defined");
        let body = class.split("\n}\n").next().unwrap_or(class);
        assert!(body.contains("super('Bad Request')"), "an empty message is not replaced by `??`, so the 400 body would be {{\"error\":\"\"}}: {body}");
    }

    #[test]
    fn typescript_error_path_cannot_itself_throw() {
        let op = ApiOperation {
            service: "Bookmarks".into(),
            port: "BookmarkApi".into(),
            method_name: "get".into(),
            operation_id: "get".into(),
            http_method: "GET".into(),
            path: "/bookmarks".into(),
            description: String::new(),
            params: vec![],
            body: None,
            success: 200,
            response: None,
            errors: vec![],
            file: "api.ts".into(),
            line: 1,
            args: vec![],
            is_async: true,
            fails: false,
            error_type: None,
            error_variants: vec![],
        };
        let contract = ApiContract {
            title: "t".into(),
            version: "1".into(),
            operations: vec![op],
            schemas: Default::default(),
        };
        let target = Target::TypeScript { import: "./api.js".into() };
        let out = generate(&contract, "BookmarkApi", &target).unwrap();
        let body = out.split("function sendError").nth(1).expect("sendError is defined");
        assert!(body.contains("headersSent"), "writeHead after headers were sent throws inside .catch: {body}");
        assert!(body.contains("Number.isInteger(status)"), "42, 1.5 and NaN make writeHead throw: {body}");
        assert!(body.contains("status >= 400 && status <= 599"), "1000 and 200 are not error codes: {body}");
        assert!(body.contains("?.message"), "a thrown null has no `message`: {body}");
    }

    #[test]
    fn typescript_path_parameter_with_bad_percent_escape_is_a_bad_request() {
        let op = ApiOperation {
            service: "Bookmarks".into(),
            port: "BookmarkApi".into(),
            method_name: "get".into(),
            operation_id: "get".into(),
            http_method: "GET".into(),
            path: "/bookmarks/{id}".into(),
            description: String::new(),
            params: vec![],
            body: None,
            success: 200,
            response: None,
            errors: vec![],
            file: "api.ts".into(),
            line: 1,
            args: vec![],
            is_async: true,
            fails: false,
            error_type: None,
            error_variants: vec![],
        };
        let contract = ApiContract {
            title: "t".into(),
            version: "1".into(),
            operations: vec![op],
            schemas: Default::default(),
        };
        let target = Target::TypeScript { import: "./api.js".into() };
        let out = generate(&contract, "BookmarkApi", &target).unwrap();
        assert!(!out.contains("= decodeURIComponent(g)"), "a bare decodeURIComponent throws URIError, answered 500");
        let helper = out.split("function decodePathSegment").nth(1).expect("decoding goes through a helper");
        let body = helper.split("\n}\n").next().unwrap_or(helper);
        assert!(body.contains("catch") && body.contains("throw new BadRequest()"), "{body}");
    }

    #[test]
    fn ts_literal_route_is_tried_before_a_parameterized_one() {
        let mk = |name: &str, path: &str| ApiOperation {
            service: "Bookmarks".into(),
            port: "BookmarkApi".into(),
            method_name: name.into(),
            operation_id: name.into(),
            http_method: "GET".into(),
            path: path.into(),
            description: String::new(),
            params: vec![],
            body: None,
            success: 200,
            response: None,
            errors: vec![],
            file: "api.ts".into(),
            line: 1,
            args: vec![],
            is_async: true,
            fails: false,
            error_type: None,
            error_variants: vec![],
        };
        let contract = ApiContract {
            title: "t".into(),
            version: "1".into(),
            operations: vec![mk("get", "/bookmarks/{id}"), mk("search", "/bookmarks/search")],
            schemas: Default::default(),
        };
        let target = Target::TypeScript { import: "./api.js".into() };
        let out = generate(&contract, "BookmarkApi", &target).unwrap();
        let literal = out.find("match('/bookmarks/search'").expect("literal route");
        let param = out.find("match('/bookmarks/{id}'").expect("param route");
        assert!(literal < param, "the literal route must be tried first");
    }

    #[test]
    fn ts_boolean_input_other_than_true_or_false_is_a_400() {
        assert_eq!(ts_convert("raw", &TypeRef::Boolean), "toBoolean(raw)");
        let op = ApiOperation {
            service: "Bookmarks".into(),
            port: "BookmarkApi".into(),
            method_name: "list".into(),
            operation_id: "list".into(),
            http_method: "GET".into(),
            path: "/bookmarks".into(),
            description: String::new(),
            params: vec![],
            body: None,
            success: 200,
            response: None,
            errors: vec![],
            file: "api.ts".into(),
            line: 1,
            args: vec![],
            is_async: true,
            fails: false,
            error_type: None,
            error_variants: vec![],
        };
        let contract = ApiContract { title: "t".into(), version: "1".into(), operations: vec![op], schemas: Default::default() };
        let target = Target::TypeScript { import: "./api.js".into() };
        let out = generate(&contract, "BookmarkApi", &target).unwrap();
        let helper = out.split("function toBoolean").nth(1).expect("booleans go through a helper");
        let body = helper.split("\n}\n").next().unwrap_or(helper);
        assert!(body.contains("'true'") && body.contains("'false'") && body.contains("throw new BadRequest()"), "{body}");
    }

    #[test]
    fn ts_integer_input_that_is_not_a_plain_integer_is_a_400() {
        assert_eq!(ts_convert("raw", &TypeRef::Integer), "toInteger(raw)");
        assert_eq!(ts_convert("raw", &TypeRef::Number), "toNumber(raw)");
        let op = ApiOperation {
            service: "Bookmarks".into(),
            port: "BookmarkApi".into(),
            method_name: "list".into(),
            operation_id: "list".into(),
            http_method: "GET".into(),
            path: "/bookmarks".into(),
            description: String::new(),
            params: vec![],
            body: None,
            success: 200,
            response: None,
            errors: vec![],
            file: "api.ts".into(),
            line: 1,
            args: vec![],
            is_async: true,
            fails: false,
            error_type: None,
            error_variants: vec![],
        };
        let contract = ApiContract { title: "t".into(), version: "1".into(), operations: vec![op], schemas: Default::default() };
        let target = Target::TypeScript { import: "./api.js".into() };
        let out = generate(&contract, "BookmarkApi", &target).unwrap();
        let helper = out.split("function toInteger").nth(1).expect("integers go through a helper");
        let body = helper.split("\n}\n").next().unwrap_or(helper);
        assert!(body.contains("[0-9]+") && body.contains("isSafeInteger") && body.contains("throw new BadRequest()"), "{body}");
    }

    #[test]
    fn ts_json_null_or_non_object_body_is_a_400_not_a_type_error() {
        let arg = |name: &str, source: ArgSource| ApiArg { name: name.into(), written: "string".into(), source, ty: TypeRef::String, required: true };
        let gen = |args: Vec<ApiArg>| {
            let op = ApiOperation {
                service: "Bookmarks".into(),
                port: "BookmarkApi".into(),
                method_name: "add".into(),
                operation_id: "add".into(),
                http_method: "POST".into(),
                path: "/bookmarks".into(),
                description: String::new(),
                params: vec![],
                body: None,
                success: 201,
                response: None,
                errors: vec![],
                file: "api.ts".into(),
                line: 1,
                args,
                is_async: true,
                fails: false,
                error_type: None,
                error_variants: vec![],
            };
            let contract = ApiContract { title: "t".into(), version: "1".into(), operations: vec![op], schemas: Default::default() };
            generate(&contract, "BookmarkApi", &Target::TypeScript { import: "./api.js".into() }).unwrap()
        };
        let fn_body = |out: &str, name: &str| {
            let helper = out.split(&format!("function {name}")).nth(1).unwrap_or_else(|| panic!("{name} is defined")).to_string();
            helper.split("\n}\n").next().unwrap_or(&helper).to_string()
        };
        let fields = gen(vec![arg("url", ArgSource::BodyField("url".into()))]);
        assert!(!fields.contains("(await readJson(req)) as Record<string, unknown>"), "an unchecked cast lets a `null` body reach `fields['url']`: TypeError, 500");
        let object = fn_body(&fields, "readObject");
        assert!(object.contains("typeof body !== 'object'") && object.contains("Array.isArray") && object.contains("throw new BadRequest()"), "{object}");
        let whole = gen(vec![arg("input", ArgSource::Body)]);
        let json = fn_body(&whole, "readJson");
        assert!(json.contains("=== null") && json.contains("throw new BadRequest()"), "a `null` body must not reach the port: {json}");
    }

    #[test]
    fn request_bodies_are_size_capped_in_go_and_ts() {
        let arg = |source: ArgSource| ApiArg { name: "input".into(), written: "string".into(), source, ty: TypeRef::String, required: true };
        let gen = |args: Vec<ApiArg>, target: Target| {
            let op = ApiOperation {
                service: "Bookmarks".into(),
                port: "BookmarkApi".into(),
                method_name: "add".into(),
                operation_id: "add".into(),
                http_method: "POST".into(),
                path: "/bookmarks".into(),
                description: String::new(),
                params: vec![],
                body: None,
                success: 201,
                response: None,
                errors: vec![],
                file: "api.ts".into(),
                line: 1,
                args,
                is_async: true,
                fails: false,
                error_type: None,
                error_variants: vec![],
            };
            let contract = ApiContract { title: "t".into(), version: "1".into(), operations: vec![op], schemas: Default::default() };
            generate(&contract, "BookmarkApi", &target).unwrap()
        };
        for source in [ArgSource::Body, ArgSource::BodyField("input".into())] {
            let go = gen(vec![arg(source)], Target::Go { import: "example.com/x/ports".into(), package: "ports".into() });
            assert!(!go.contains("json.NewDecoder(r.Body)"), "an unbounded body read is an OOM: {go}");
            assert!(go.contains("decodeBody(w, r, &") && go.contains("http.MaxBytesReader(w, r.Body, maxBodyBytes)"), "{go}");
        }
        let ts = gen(vec![arg(ArgSource::Body)], Target::TypeScript { import: "./api.js".into() });
        let read = ts.split("function readJson").nth(1).unwrap().split("\n}\n").next().unwrap();
        assert!(read.contains("MAX_BODY_BYTES") && read.contains("throw new PayloadTooLarge()"), "{read}");
        assert!(read.find("PayloadTooLarge").unwrap() < read.find("chunks.push").unwrap(), "the cap must be checked before buffering: {read}");
    }
}
