//! What generated a project, written into the project as it is generated.
//!
//! ADR-2609221900. The examples in this repository record their test counts and
//! nothing about what produced them — no model, no date, no version. That is
//! unrecoverable: the runs and the machines are gone, and a guess wearing a date
//! would be worse than the silence, because it would look like a record.
//!
//! So the record is written during the run, not reconstructed after it. The
//! careful part is not writing a file; it is writing one that claims no more
//! than the runner knows.

use std::path::Path;

pub use crate::ports::Facts;


/// The provenance document for a run.
///
/// Pure: the same facts give the same text, and a test needs no model, no
/// network and no build (ADR-2609221900 §5).
pub fn record(f: &Facts) -> String {
    let mut s = String::new();
    s.push_str("# Provenance\n\n");
    s.push_str(
        "This project was generated by hexa. This file was written by the run that\n\
         generated it, not added afterwards.\n\n",
    );

    s.push_str("| | |\n|---|---|\n");
    s.push_str(&format!("| Generated | {} |\n", f.date_utc));
    s.push_str(&format!("| hexa version | {} |\n", f.hexa_version));
    s.push_str(&format!(
        "| Gate | `{}` |\n",
        if f.gate.is_empty() { "none recorded" } else { &f.gate }
    ));
    s.push_str(&format!(
        "| Gate result | {} |\n",
        if f.gate_passed { "passed" } else { "**did not pass**" }
    ));
    s.push_str(&format!("| Designs proposed | {} |\n", f.designs));
    s.push_str(&format!("| Critiques | {} |\n", f.critiques));
    s.push('\n');

    s.push_str("## The challenge, as given\n\n");
    s.push_str(&format!("> {}\n\n", f.challenge.trim()));

    s.push_str("## Inference this run resolved\n\n");
    if f.tiers.is_empty() && f.react_models.is_empty() {
        s.push_str(
            "**None.** No tier resolved to a model when this run started. That is\n\
             recorded rather than omitted: a file that simply listed nothing would\n\
             read the same as one where nothing was checked.\n\n",
        );
    } else {
        if f.tiers.is_empty() {
            s.push_str("No tier resolved to a model.\n\n");
        } else {
            s.push_str("| Tier | Model |\n|---|---|\n");
            for (tier, model) in &f.tiers {
                s.push_str(&format!("| {tier} | {model} |\n"));
            }
            s.push('\n');
        }
        if f.react_models.is_empty() {
            s.push_str("The do-loop had no candidate models configured.\n\n");
        } else {
            s.push_str("Do-loop candidates, in preference order:\n\n");
            for m in &f.react_models {
                s.push_str(&format!("- {m}\n"));
            }
            s.push('\n');
        }
    }

    // The limit is part of the record, not a footnote to it, and it is stated
    // whether or not everything resolved — it describes what was never
    // measured, not what failed (§3).
    s.push_str("## What this record does not say\n\n");
    s.push_str(
        "These are the models this run **resolved**, read from configuration when it\n\
         started. They are not a claim about which model answered any particular\n\
         call. hexa resolves a tier at dispatch and does not record the answer's\n\
         origin, so a call that fell back to another tier is **not distinguished**\n\
         here from one that did not.\n\n\
         Read this as what was available to the run, not as authorship.\n",
    );
    s
}

/// Write [`record`] to `PROVENANCE.md` in `dir`, creating `dir` if the build
/// did not get far enough to make it.
pub fn write(dir: &Path, f: &Facts) -> std::io::Result<()> {
    std::fs::create_dir_all(dir)?;
    std::fs::write(dir.join("PROVENANCE.md"), record(f))
}

/// [`Provenance`](crate::ports::Provenance) as `PROVENANCE.md` in the target.
pub struct ProvenanceFile;

impl crate::ports::Provenance for ProvenanceFile {
    fn write(&self, dir: &Path, facts: &Facts) -> std::io::Result<()> {
        write(dir, facts)
    }
}

